global:
    hostname: mygen3dev.se4.bio
    dev: true

# -- (map) Configurations for frontend-framework chart.
frontend-framework:
  # -- (bool) Whether to deploy the frontend-framework subchart.
  enabled: false
  # -- (map) Docker image information.
  image:
    # -- (string) The Docker image repository for the frontend-framework.
    repository: "quay.io/cdis/commons-frontend-app"
    # -- (string) Overrides the image tag whose default is the chart appVersion.
    tag: "main"

fence:
    FENCE_CONFIG:
        MOCK_AUTH: true

# DISABLE some (for now) unnecessary services:

audit:
  enabled: false

guppy:
  enabled: false

hatchery:
  enabled: false

manifestservice:
  enabled: false

metadata:
  enabled: false

wts:
  enabled: false