global:
    hostname: mygen3dev.se4.bio
    dev: true
    # set to "gen3ff" for the new frontend-framework (instead of old data-portal)
    frontendRoot: gen3ff

# -- (map) Configurations for frontend-framework chart.
frontend-framework:
  # -- (bool) Whether to deploy the frontend-framework subchart.
  enabled: true
  # -- (map) Docker image information.
  image:
    # -- (string) The Docker image repository for the frontend-framework.
    repository: "quay.io/cdis/commons-frontend-app"
    # -- (string) Overrides the image tag whose default is the chart appVersion.
    tag: "main"

fence:
    FENCE_CONFIG:
        MOCK_AUTH: true
  # TODO - Enable this fence section instead when integrating with real auth:
  # usersync:
  #   usersync: true
  #   userYamlS3Path: s3://REPLACEME/user.yaml
  # enabled: true
  # externalSecrets:
  #   fenceConfig: my-REPLACEME-kube-secret-fence-config
  #   fenceJwtKeys: my-REPLACEME-kube-fence-jwt

# DISABLE some (for now) unnecessary services:

audit:
  enabled: false

guppy:
  enabled: false

hatchery:
  enabled: false

manifestservice:
  enabled: false

metadata:
  enabled: false

# legacy portal disabled in favor of new frontend-framework:
portal:
  enabled: false

wts:
  enabled: false